### ISSUE TITLE
Subscription implmentation

### ISSUE THREAD

**Issue by shaivyanegi** [HackerGens/GoogleBillingAndroid#1]
Hey Sajjad !! What? If I would like to implement Subscription with three options like 1 month, 3 months, 6 months

I think, I just need to add, SUBS in place of INAPP. Am I right ?

I simply want to hide and show button, if subscription purchased then hide button and if subscription not purchased then show button

**Comment by HackerGens** [comment]
hi i have seen your email.sorry for the late reply did your problem are
resolved are not.

**Comment by HackerGens** [comment]
No reply from shaivyanegi
